name: build and production client to dockerhub

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      secrets:
        DOKERHUB_USERNAME:
          required: true
        DOKERHUB_TOKEN:
        required: true

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          plateforms: linux/amd64,linux/arm64
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.secrets.DOKERHUB_USERNAME }}
          password: ${{ inputs.secrets.DOKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          context: "{{defaultContext}}:frontend"
          file: "Dockerfile.prod"
          tags: ${{ inputs.image_name }}
          cache-front: type=gha
          cache-to: type=gha, node=max