name: Compile and push client and server to staging environment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  client-tests:
    uses: ComicScrip/cda-nov25-p2-g2/.github/workflows/test-frontend.yml@main

  build-and-push-server:
    uses: ComicScrip/cda-nov25-p2-g2/.github/workflows/build-backend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: babyboard/cda-nov25-p2-g2-back:prod

  build-and-push-client:
    needs:
      - client-tests
    uses: ComicScrip/cda-nov25-p2-g2/.github/workflows/build-frontend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: babyboard/cda-nov25-p2-g2-front:prod

  notify-vps:
    needs:
      - build-and-push-server
      - build-and-push-client
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook on VPS
        run: |
          curl -X POST \
            -H "X-Webhook-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            https://ops.cda-nov25-p2g2.duckdns.org/hooks/redeploy-babyboard-prod